<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" href="{$basePath}/imgs/fav.ico">
      <link rel="stylesheet" type="text/css" href="/stylesheet/Error/500.css">
      <link href="https://fonts.googleapis.com/css?family=Muli:300,400,600" rel="stylesheet">
      <title>500 | Podlahyavere.sk</title>
  </head>
  <body>
    <div class="container text-center">
       <div class="row"><h1>Error 500!</h1></div>
       <div class="row"><p> Nieco sa na nasej strane pokazilo. <br> Neboj sa, nieje to tvoja chyba, ale nasa. O chvilu sme naspat. </p></div>
       <div class="row">
       <a href="/">
        <img src="/imgs/please-stand-by.png" alt="logo">
       </a>
       </div>
    </div>
  </body>
</html>